### ISSUE TITLE
QUESTION: Why do omp binary refer to samp03svr ?? 

### ISSUE THREAD

**Issue by Zorono** [sampctl/runtimes#19]
https://github.com/sampctl/runtimes/blob/c904d1f7dda5c54d9f64b1ec8c5bb619cf5cce41/runtimes.json#L38

**Comment by MeIsAlan** [comment]
shit actually, why?

**Comment by Cheaterman** [comment]
It's so over.

**Comment by ADRFranklin** [comment]
we do this because sampctl currently has the binary names hardcoded into them, as this decision was made before openmp was a thing. 

Basically by renaming it to the sa-mp binaries, we can make sure it loads, else sampctl wouldn't know what to do with it, and since it's basically backwards compatible with sa-mp, it makes sense to do this.
